Prototype pollution fix - checking magic attributes
418sec/next-object-operator pull request #1
Opened 2021-01-15 12:16 UTC by d3v53c

### 📊 Metadata *

@feizheng/next-object-operator is vulnerable to Prototype Pollution. This package fails to restrict access to prototypes of objects, allowing for modification of prototype behavior using a proto payload, which may result in Sensitive Information Disclosure/Denial of Service(DoS)/Remote Code Execution.

#### Bounty URL: https://www.huntr.dev/bounties/1-npm-%40feizheng%2Fnext-object-operator/

### ⚙️ Description *

Prototype Pollution refers to the ability to inject properties into existing JavaScript language construct prototypes, such as objects.
JavaScript allows all Object attributes to be altered, including their magical attributes such as proto, constructor and prototype.
An attacker manipulates these attributes to overwrite, or pollute, a JavaScript application object prototype of the base object by injecting other values.
Properties on the Object.prototype are then inherited by all the JavaScript objects through the prototype chain.

### 💻 Technical Description *

Fixed by avoiding setting magical attributes. The bug is fixed by validating the input strArray to check for prototypes. It is implemented by a simple validation to check for prototype keywords (proto, constructor and prototype), where if it exists, the function returns the object without modifying it, thus fixing the Prototype Pollution Vulnerability.

### 🐛 Proof of Concept (PoC) *

Create the following PoC file:

```
// poc.js
var nextObjectOperator = require("@feizheng/next-object-operator")

const data = {};
const operator = new nextObjectOperator(data);

console.log("Before : " + {}.polluted);
operator.set('__proto__.polluted', 'Yes! Its Polluted')
console.log("After : " + {}.polluted);
```

Execute the following commands in another terminal:

```
npm i @feizheng/next-object-operator # Install affected module
node poc.js #  Run the PoC
```

Check the Output:

```
Before : undefined
After : Yes! Its Polluted
```

### 🔥 Proof of Fix (PoF) *

Before:

![image](https://user-images.githubusercontent.com/64132745/104725911-c2b03b00-5758-11eb-9e75-68ce7df6707c.png)

After:

![image](https://user-images.githubusercontent.com/64132745/104725987-e4a9bd80-5758-11eb-8cc4-ee0d5bb0a036.png)

### 👍 User Acceptance Testing (UAT)

![image](https://user-images.githubusercontent.com/64132745/104726398-88936900-5759-11eb-9e91-743ed5c07a13.png)

After the fix, functionality is unaffected.

### 🔗 Relates to...

https://www.huntr.dev/bounties/1-npm-%40feizheng%2Fnext-object-operator/

2021-01-16 04:08 UTC, mzfr approved these changes
LGTM! :+1:

2021-01-17 14:26 UTC, Mik317 requested changes
Unfortunately it'is still vulnerable :cry:
![Screenshot from 2021-01-17 15-21-49](https://user-images.githubusercontent.com/33063403/104845962-63793480-58d8-11eb-9091-7c1cbbea9f62.png)

Cheers,
Mik

2021-01-17 16:48 UTC, d3v53c commented
> Unfortunately it'is still vulnerable 😢
> ![Screenshot from 2021-01-17 15-21-49](https://user-images.githubusercontent.com/33063403/104845962-63793480-58d8-11eb-9091-7c1cbbea9f62.png)
> 
> Cheers,
> Mik

Thank you for pointing it out. Let me have a look again. Will update with relevant changes.

Cheers!!

2021-01-17 17:48 UTC, d3v53c commented
Hi @Mik317 ,

I just ran the same code from my branch, seems no issues. I'm sorry, maybe I'm not seeing the issue here. I'll add my screenshots for further clarification.

![image](https://user-images.githubusercontent.com/64132745/104850658-5f6c0780-5916-11eb-9341-12bb4ec704b1.png)

![image](https://user-images.githubusercontent.com/64132745/104850689-8fb3a600-5916-11eb-8e5e-675d086041bb.png)

![image](https://user-images.githubusercontent.com/64132745/104851270-161db700-591a-11eb-894f-efbf97fa3f66.png)

Could you please try again, after running `npm run build`?
I'm just shooting my thoughts here.

Cheers!!

2021-01-18 11:32 UTC, Mik317 approved these changes
LGTM :smile: :cake:
Thanks for the information :+1: 

Cheers,
Mik

2021-01-21 15:36 UTC, merged

2021-01-21 15:36 UTC, huntr-helper commented
Congratulations d3v53c - your fix has been selected! 🎉

Thanks for being part of the community & helping secure the world's open source code.
If you have any questions, please respond in the comments section, or hit us up on Discord. Your bounty is on its way - keep hunting!

[Come join us on Discord](https://huntr.dev/discord)